require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::SlidersController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Slider. As you add validations to Admin::Slider, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::SlidersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_sliders as @admin_sliders" do
      slider = Admin::Slider.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_sliders).should eq([slider])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_slider as @admin_slider" do
      slider = Admin::Slider.create! valid_attributes
      get :show, {:id => slider.to_param}, valid_session
      assigns(:admin_slider).should eq(slider)
    end
  end

  describe "GET new" do
    it "assigns a new admin_slider as @admin_slider" do
      get :new, {}, valid_session
      assigns(:admin_slider).should be_a_new(Admin::Slider)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_slider as @admin_slider" do
      slider = Admin::Slider.create! valid_attributes
      get :edit, {:id => slider.to_param}, valid_session
      assigns(:admin_slider).should eq(slider)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Slider" do
        expect {
          post :create, {:admin_slider => valid_attributes}, valid_session
        }.to change(Admin::Slider, :count).by(1)
      end

      it "assigns a newly created admin_slider as @admin_slider" do
        post :create, {:admin_slider => valid_attributes}, valid_session
        assigns(:admin_slider).should be_a(Admin::Slider)
        assigns(:admin_slider).should be_persisted
      end

      it "redirects to the created admin_slider" do
        post :create, {:admin_slider => valid_attributes}, valid_session
        response.should redirect_to(Admin::Slider.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_slider as @admin_slider" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Slider.any_instance.stub(:save).and_return(false)
        post :create, {:admin_slider => {  }}, valid_session
        assigns(:admin_slider).should be_a_new(Admin::Slider)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Slider.any_instance.stub(:save).and_return(false)
        post :create, {:admin_slider => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_slider" do
        slider = Admin::Slider.create! valid_attributes
        # Assuming there are no other admin_sliders in the database, this
        # specifies that the Admin::Slider created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Slider.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => slider.to_param, :admin_slider => { "these" => "params" }}, valid_session
      end

      it "assigns the requested admin_slider as @admin_slider" do
        slider = Admin::Slider.create! valid_attributes
        put :update, {:id => slider.to_param, :admin_slider => valid_attributes}, valid_session
        assigns(:admin_slider).should eq(slider)
      end

      it "redirects to the admin_slider" do
        slider = Admin::Slider.create! valid_attributes
        put :update, {:id => slider.to_param, :admin_slider => valid_attributes}, valid_session
        response.should redirect_to(slider)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_slider as @admin_slider" do
        slider = Admin::Slider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Slider.any_instance.stub(:save).and_return(false)
        put :update, {:id => slider.to_param, :admin_slider => {  }}, valid_session
        assigns(:admin_slider).should eq(slider)
      end

      it "re-renders the 'edit' template" do
        slider = Admin::Slider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Slider.any_instance.stub(:save).and_return(false)
        put :update, {:id => slider.to_param, :admin_slider => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_slider" do
      slider = Admin::Slider.create! valid_attributes
      expect {
        delete :destroy, {:id => slider.to_param}, valid_session
      }.to change(Admin::Slider, :count).by(-1)
    end

    it "redirects to the admin_sliders list" do
      slider = Admin::Slider.create! valid_attributes
      delete :destroy, {:id => slider.to_param}, valid_session
      response.should redirect_to(admin_sliders_url)
    end
  end

end
