development:
  adapter: postgresql
  database: rock_dev
  username: nazar
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: rock_test
  username: nazar
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: rock_prod
  username: root
  pool: 5
  timeout: 5000
